JumpToFlask/myproject/pybo/views/auth_views.py
# 인증화면 view

from flask import Blueprint, url_for, render_template, flash, request, session, g
from werkzeug.security import generate_password_hash, check_password_hash
from werkzeug.utils import redirect

import functools
from ..db import db
from pybo.forms import UserCreateForm, UserLoginForm

bp = Blueprint('auth', __name__, url_prefix='/auth')

@bp.route('/signup/', methods=('GET', 'POST'))
def signup():
    form = UserCreateForm() #userform에서 불러옴
    cursor = db.cursor()
    if request.method == 'POST' and form.validate_on_submit():
        
        
        sql = "select * from user where username='{}'".format(form.username.data)
        cursor.execute(sql)
        user = cursor.fetchone()
        # ---- ID 조회 ---#
        if not user:
            sql = "insert into user (username, password, email) values ('{}','{}','{}');".format(form.username.data, generate_password_hash(form.password1.data), form.email.data)
            # 사용자 password를 평문이 아닌 hash처리해서 보여줌!
            cursor.execute(sql)
            db.commit()
            # database에 commit!
            return redirect(url_for('main.index'))
        
        
        else:
            flash('이미 존재하는 사용자입니다.')
            # 회원가입하는 쪽에 error 메시지로 출력
            
            
            #가입 요청이 get으로 들어오면 return으로 바로옴 (위의 if문은 post요청)
    return render_template('auth/signup.html', form=form)


@bp.route('/login/', methods=('GET', 'POST'))
def login():
    form = UserLoginForm()
    cursor = db.cursor()
    if request.method == 'POST' and form.validate_on_submit():
        error = None
        sql = "select * from user where username='{}'".format(form.username.data)
        cursor.execute(sql)
        user = cursor.fetchone()
        if not user: #user가 없을 때,
            error = "존재하지 않는 사용자입니다."
        elif not check_password_hash(user['password'], form.password.data):
            # (db에 존재한 user 패스워드와 입력받은 패스워드의 비교)
            error = "비밀번호가 올바르지 않습니다."
        if error is None:
            session.clear()
            session['user_id'] = user['id']
            session['username'] = user['username']
            return redirect(url_for('main.index'))
        # session을 발급하여 user의 id값과 username을 담아둠. ; 로그인 권한이 필요한 페이지에서 session key가 전달, 권한 인정 (session은 서버에서 관리 후 파기)
        
        flash(error)
    return render_template('auth/login.html', form=form)



@bp.before_app_request
def load_logged_in_user():
    user_id = session.get('user_id')
    if user_id is None:
        g.user = None # 전역객체인 g.user에 담음
    else:
        g.user = {'user_id': session.get('user_id'), 'username': session['username']}
        print(g.user)



@bp.route('/logout/')
def logout():
    session.clear()
    return redirect(url_for('main.index'))

JumpToFlask/myproject/pybo/templates/base.html
<html lang="ko">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />
    <!-- Bootstrap CSS -->
    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='bootstrap.min.css') }}"
    />
    <!-- pybo CSS -->
    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='style.css') }}"
    />
    <title>Hello, pybo!</title>
  </head>
  <body>
    <!-- 네비게이션바 -->
    {% include "navbar.html" %}
    <!-- 캐러셀 같은 경우도 이와같이 include를 이용하여 따로 관리-->
    <!-- 기본 템플릿 안에 삽입될 내용 Start -->
    {% block content %} {% endblock %}
    <!-- 기본 템플릿 안에 삽입될 내용 End -->

    <!-- Bootstrap JS -->
    <script src="{{ url_for('static', filename='bootstrap.min.js') }}"></script>
  </body>
</html>

JumpToFlask/myproject/pybo/templates/form_errors.html
<!-- 필드오류 -->
{% if form.errors %}
<div class="alert alert-danger" role="alert">
  {% for field, errors in form.errors.items() %}
  <strong>{{ form[field].label }}</strong>
  <ul>
    {% for error in errors %}
    <li>{{ error }}</li>
    {% endfor %}
  </ul>
  {% endfor %}
</div>
{% endif %}
<!-- flash 오류 -->
{% for message in get_flashed_messages() %}
<div class="alert alert-danger" role="alert">{{ message }}</div>
{% endfor %}

JumpToFlask/myproject/pybo/templates/navbar.html
<!-- 네비게이션바 -->
<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
  <div class="container-fluid">
    <a class="navbar-brand" href="{{ url_for('main.index') }}">Pybo</a>
    <button
      class="navbar-toggler"
      type="button"
      data-bs-toggle="collapse"
      data-bs-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      {% if g.user %}
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('auth.logout') }}"
            >{{ g.user.username }} / 로그아웃</a
          >
        </li>
      </ul>
      {% else %}
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('auth.signup') }}">계정생성</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('auth.login') }}">로그인</a>
        </li>
      </ul>
      {% endif %}
    </div>
  </div>
</nav>