JumpToFlask/myproject/pybo/views/answer_views.py
from ..db import db
from datetime import datetime
from flask import Blueprint, render_template, url_for, redirect, request, g
from ..forms import AnswerForm

bp = Blueprint('answer', __name__, url_prefix='/answer')

@bp.route('/create/<int:question_id>', methods=('POST',))
def create(question_id):
    
    if g.user is None:
        return redirect(url_for('auth.login'))
    
    form = AnswerForm()
    if form.validate_on_submit():
        cursor = db.cursor()
        content = request.form['content']
        sql = "insert into answer (question_id, content, create_date, user_id) values ({},'{}','{}',{})".format(question_id, content, datetime.now(), g.user['user_id'])
        cursor.execute(sql)
        db.commit()
        
        return redirect(url_for('question.detail', question_id=question_id))
    
        
    cursor = db.cursor()
    sql = 'SELECT * FROM question WHERE id={};'.format(question_id)
    cursor.execute(sql)
    question = cursor.fetchone()
    
    sql = 'SELECT * FROM answer WHERE question_id={}'.format(question_id)
    cursor.execute(sql)
    answer_set = cursor.fetchall()
    
    
    return render_template('question/question_detail.html', question=question, form=form, answer_set=answer_set)




@bp.route('/modify/<int:answer_id>', methods=('GET', 'POST'))
def modify(answer_id):
    cursor = db.cursor()
    sql = "SELECT * FROM answer WHERE id = {}".format(answer_id)
    cursor.execute(sql)
    answer = cursor.fetchone()
    if g.user['user_id'] != answer['user_id']:
        flash('수정권한이 없습니다')
        return redirect(url_for('question.detail', question_id=answer.question.id))
    if request.method == "POST":
        form = AnswerForm()
        if form.validate_on_submit():
            cursor = db.cursor()
            sql = "update answer set content='{}', modify_date='{}' where id={};".format(form.content.data, datetime.now(), answer_id) 
            cursor.execute(sql)
            db.commit()
            return redirect(url_for('question.detail', question_id=answer['question_id']))
    else:
        form = AnswerForm(content=answer['content'])
    return render_template('answer/answer_form.html', form=form)



@bp.route('/delete/<int:answer_id>')
def delete(answer_id):
    cursor = db.cursor()
    sql = "SELECT * FROM answer WHERE id = {}".format(answer_id)
    cursor.execute(sql)
    answer = cursor.fetchone()
    question_id = answer['question_id']
    if g.user['user_id'] != answer['user_id']:
        flash('삭제권한이 없습니다')
    else:
        sql = "delete from answer where id={}".format(answer_id)
        cursor.execute(sql)
        db.commit()
    return redirect(url_for('question.detail', question_id=question_id))

JumpToFlask/myproject/pybo/views/question_views.py
from flask import Blueprint, render_template,  url_for, redirect, request, g
from ..db import db
from pybo.forms import QuestionForm, AnswerForm
from datetime import datetime



bp = Blueprint('question', __name__, url_prefix='/question')

@bp.route('/list/')
def _list():
    question_list = {}
    number = 5
    page = request.args.get('page', type=int, default = 1)
    cursor = db.cursor()
    
    
    sql = """
    SELECT T.*, U.username FROM 
    (SELECT Q.*, IFNULL(A.count,0) AS count
    FROM question AS Q 
    LEFT JOIN (SELECT count(*) AS count, question_id FROM answer GROUP BY question_id) AS A 
    ON Q.id = A.question_id) AS T 
    LEFT JOIN user AS U 
    ON T.user_id = U.id
    ORDER BY Q.id desc LIMIT {} OFFSET {};
		""".format(number, number * (page - 1))
    cursor.execute(sql)
    item = cursor.fetchall()

    
    sql = 'SELECT COUNT(*) as count FROM question;'
    cursor.execute(sql)
    get_length = cursor.fetchone()
    #print(get_length)
    
    max_page = (get_length['count'] - 1) // number + 1
    #print(max_page)
    question_list['item'] = item
    question_list['max_page'] = list(range(1,max_page+1))
    question_list['page'] = page
    question_list['total'] = get_length['count']
    question_list['number'] = number
    
    

    return render_template('question/question_list.html', question_list=question_list)

@bp.route('/detail/<int:question_id>/')
def detail(question_id):
    form = AnswerForm()
    cursor = db.cursor()
    sql = """
        SELECT Q.*, U.username FROM 
        (SELECT * FROM question WHERE id={}) AS Q
        LEFT JOIN user AS U
        ON Q.user_id=U.id;
        """.format(question_id)
    cursor.execute(sql)
    question = cursor.fetchone()
    
    sql = """
        SELECT A.*, U.username FROM
        (SELECT * FROM answer WHERE question_id ={}) AS A
        LEFT JOIN user AS U 
        ON A.user_id=U.id;
        """.format(question_id)
    cursor.execute(sql)
    answer_set= cursor.fetchall()
    
        
    return render_template('question/question_detail.html',  question=question, answer_set = answer_set, form=form)



@bp.route('/create/', methods=('GET', 'POST'))
def create():
    
    if g.user is None:
        return redirect(url_for('auth.login'))
      
    form = QuestionForm()
    if request.method == "POST" and form.validate_on_submit():
        cursor = db.cursor()
        sql = "insert into question (subject, content, create_date, user_id) values ('{}','{}','{}',{})".format(form.subject.data, form.content.data, datetime.now(), g.user['user_id'])
        cursor.execute(sql)
        db.commit()
        return redirect(url_for('main.index'))
    return render_template('question/question_form.html', form=form)
  
  


@bp.route('/modify/<int:question_id>', methods=('GET', 'POST'))
def modify(question_id):
    cursor = db.cursor()
    sql = "select * from question where id={}".format(question_id)
    cursor.execute(sql)
    question = cursor.fetchone()
    
    if g.user['user_id'] != question['user_id']:
        flash('수정권한이 없습니다')
        return redirect(url_for('question.detail', question_id=question_id))
    if request.method == 'POST':  # POST 요청
        form = QuestionForm()
        if form.validate_on_submit():
            cursor = db.cursor()
            sql = "update question set subject='{}', content='{}', modify_date='{}' where id={};".format(form.subject.data, form.content.data, datetime.now(), question_id) 
            cursor.execute(sql)
            db.commit()
            return redirect(url_for('question.detail', question_id=question_id))
    else:  # GET 요청
        form = QuestionForm(subject=question['subject'], content=question['content'])
    return render_template('question/question_form.html', form=form)
  
  
  
@bp.route('/delete/<int:question_id>')
def delete(question_id):
    cursor = db.cursor()
    sql = "select * from question where id={}".format(question_id)
    cursor.execute(sql)
    question = cursor.fetchone()
    if g.user['user_id'] != question['user_id']:
        flash('삭제권한이 없습니다')
        return redirect(url_for('question.detail', question_id=question_id))
    sql = "delete from question where id={}".format(question_id)
    cursor.execute(sql)
    db.commit()
    return redirect(url_for('question._list'))

JumpToFlask/myproject/pybo/templates/question/question_detail.html
{% extends 'base.html' %} {% block content %}

<div class="container my-3">
  <!-- 질문 -->
  <h2 class="border-bottom py-2">{{ question.subject }}</h2>
  <div class="card my-3">
    <div class="card-body">
      <div class="card-text" style="white-space: pre-line">
        {{ question.content }}
      </div>
      <div class="d-flex justify-content-end">
        {% if question.modify_date %}
        <div class="badge bg-light text-dark p-2 text-start mx-3">
          <div class="mb-2">수정일시</div>
          <div>{{ question.modify_date|datetime }}</div>
        </div>
        {% endif %}
        <div class="badge bg-light text-dark p-2">
          <div class="mb-2">{{ question.username }}</div>
          {{ question.create_date|datetime }}
        </div>
      </div>
      <div class="my-3">
        {% if g.user.user_id == question.user_id %}
        <a
          href="{{ url_for('question.modify', question_id=question.id) }}"
          class="btn btn-sm btn-outline-secondary"
          >수정</a
        >
        <a
          href="javascript:void(0)"
          class="delete btn btn-sm btn-outline-secondary"
          data-uri="{{ url_for('question.delete', question_id=question.id) }}"
          >삭제</a
        >
        {% endif %}
      </div>
    </div>
  </div>
  <!-- 답변 목록 -->
  <h5 class="border-bottom my-3 py-2">
    {{ answer_set|length }}개의 답변이 있습니다.
  </h5>
  {% for answer in answer_set %}
  <div class="card my-3">
    <div class="card-body">
      <div class="card-text" style="white-space: pre-line">
        {{ answer.content }}
      </div>
      <div class="d-flex justify-content-end">
        {% if answer.modify_date %}
        <div class="badge bg-light text-dark p-2 text-start mx-3">
          <div class="mb-2">수정일시</div>
          <div>{{ answer.modify_date|datetime }}</div>
        </div>
        {% endif %}
        <div class="badge bg-light text-dark p-2">
          <div class="mb-2">{{ answer.username }}</div>
          {{ answer.create_date|datetime }}
        </div>
      </div>

      <div class="my-3">
        {% if g.user.user_id == answer.user_id %}
        <a
          href="{{ url_for('answer.modify', answer_id=answer.id) }}"
          class="btn btn-sm btn-outline-secondary"
          >수정</a
        >
        <a
          href="#"
          class="delete btn btn-sm btn-outline-secondary"
          data-uri="{{ url_for('answer.delete', answer_id=answer.id) }}"
          >삭제</a
        >
        {% endif %}
      </div>
    </div>
  </div>
  {% endfor %}
  <!-- 답변 등록 -->
  <form
    action="{{ url_for('answer.create', question_id=question.id) }}"
    method="post"
    class="my-3"
  >
    {{ form.csrf_token }}
    <!-- 오류표시 Start -->
    {% if form.errors %}
    <div class="alert alert-danger" role="alert">
      {% for field, errors in form.errors.items() %}
      <strong>{{ form[field].label }}</strong>
      <ul>
        {% for error in errors %}
        <li>{{ error }}</li>
        {% endfor %}
      </ul>
      {% endfor %}
    </div>
    {% endif %}
    <!-- 오류표시 End -->
    <div class="mb-3">
      <textarea
        {%
        if
        not
        g.user
        %}disabled{%
        endif
        %}
        name="content"
        id="content"
        class="form-control"
        rows="10"
      ></textarea>
    </div>
    <input type="submit" value="답변등록" class="btn btn-primary" />
  </form>
</div>
{% block script %}
<script type="text/javascript">
  const delete_elements = document.getElementsByClassName("delete");
  Array.from(delete_elements).forEach(function (element) {
    element.addEventListener("click", function () {
      if (confirm("정말로 삭제하시겠습니까?")) {
        location.href = this.dataset.uri;
      }
    });
  });
</script>
{% endblock %} {% endblock %}

JumpToFlask/myproject/pybo/templates/question/question_form.html
{% extends 'base.html' %} {% block content %}
<!-- 질문 등록 -->
<div class="container">
  <h5 class="my-3 border-bottom pb-2">질문등록</h5>
  <form method="post" class="my-3">
    {{ form.csrf_token }}
    <!-- 오류표시 Start -->
    {% if form.errors %}
    <div class="alert alert-danger" role="alert">
      {% for field, errors in form.errors.items() %}
      <strong>{{ form[field].label }}</strong>
      <ul>
        {% for error in errors %}
        <li>{{ error }}</li>
        {% endfor %}
      </ul>
      {% endfor %}
    </div>
    {% endif %}
    <!-- 오류표시 End -->
    <div class="mb-3">
      <label for="subject">제목</label>
      <input
        type="text"
        class="form-control"
        name="subject"
        id="subject"
        value="{{ form.subject.data or '' }}"
      />
    </div>
    <div class="mb-3">
      <label for="content">내용</label>
      <textarea class="form-control" name="content" id="content" rows="10">
{{ form.content.data or ''}}</textarea
      >
    </div>
    <button type="submit" class="btn btn-primary">저장하기</button>
  </form>
</div>
{% endblock %}

JumpToFlask/myproject/pybo/templates/question/question_list.html
{% extends 'base.html' %} {% block content %}
<div class="container my-3">
  <table class="table">
    <thead>
      <tr class="table-dark">
        <th>번호</th>
        <th>제목</th>
        <th>글쓴이</th>
        <th>답글 수</th>
        <th>작성일시</th>
      </tr>
    </thead>
    <tbody>
      {% if question_list.item %} {% for question in question_list.item %}
      <tr>
        <td>
          {{ question_list.total - (question_list.page - 1) *
          question_list.number - loop.index0 }}
        </td>
        <td>
          <a href="{{ url_for('question.detail', question_id=question.id) }}"
            >{{ question.subject }}</a
          >
        </td>

        <td>{{ question.username }}</td>

        <td>{{ question.count }}</td>

        <td>{{ question.create_date|datetime }}</td>
      </tr>
      {% endfor %} {% else %}
      <tr>
        <td colspan="3">질문이 없습니다.</td>
      </tr>
      {% endif %}
    </tbody>
  </table>
  <!-- 페이징처리 시작 -->
  <ul class="pagination justify-content-center">
    <!-- 페이지번호 -->

    <li
      class="btn btn-warning btn-sm"
      style="display: flex; align-items: center; border-radius: 0"
      aria-current="first_page"
    >
      <a class="btn-warning" style="text-decoration: none" href="?page=1"><<</a>
    </li>
    {% for page_num in question_list.max_page %} {% if page_num ==
    question_list.page %}
    <li class="page-item active" aria-current="page">
      <a class="page-link" href="javascript:void(0)">{{ page_num }}</a>
    </li>
    {% elif -5 < page_num - question_list.page < 5 %}
    <li class="page-item">
      <a class="page-link" href="?page={{ page_num }}">{{ page_num }}</a>
    </li>
    {% endif %} {% endfor %}
    <li
      class="btn btn-danger btn-sm"
      style="display: flex; align-items: center; border-radius: 0"
      aria-current="last_page"
    >
      <a
        class="btn-danger"
        style="text-decoration: none"
        href="?page={{question_list.max_page[-1]}}"
      >
        >>
      </a>
    </li>
  </ul>
  <!-- 페이징처리 끝 -->

  <a href="{{ url_for('question.create') }}" class="btn btn-primary"
    >질문 등록하기</a
  >
</div>
{% endblock %}